### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by LooollDoes** [SirFaizdat/Prison#80]
I really want to make a prison server but the plugin doesn't load!
im on bukkit 1.8.8

**Comment by LooollDoes** [comment]
reply pls!!

**Comment by Skurdyy** [comment]
Bump.

I cannot get mine to load either I'm running spigot 1.8.8. And I even disabled all of my plugins to see if it would work or if it was just another plugin corruption. But it still wasn't working please assist us we need help for the reason why it won't load the prison plugin I'm willing to record and show you guys or give you information that you guys need, I understand you coders think we typed something wrong but, all of my other plugins start up fine, except prison 2. When I type /pl to see my plugins list on my server it's not there. Please help thank you! 😁

**Comment by Skurdyy** [comment]
Nvm, I Figured out what the problem was i went to Faizdat's GitHUB files and saw the dependencies that Prison 2 Need. Following Plugins Need'ed to run Prison 2: World Edit, Spigot 1.8.X, Vault.
If you need the links here they are @LooollDoes 
1 Vault - http://dev.bukkit.org/bukkit-plugins/vault/files/52-vault-1-5-6/
2 World Edit - http://dev.bukkit.org/bukkit-plugins/worldedit/files/61-world-edit-6-1-up-to-mc-1-8-7/
3 Spigot 1.8 First Link For BuildTools.Jar (need'd to Compile a spigot.jar to run your server) https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar And if you do not know how to use this https://www.spigotmc.org/wiki/buildtools/#tools there's the Tutorial thanks again! hope'd this helped you! :)

**Comment by SirFaizdat** [comment]
Sorry! I forgot to include the dependencies in the plugin's overview. That's been fixed though :)
